### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by HawaiianSnow1337** [ZQiu233/QTRHacker#10]
Hey  is there anyway i can fix this by myself ? 
![issue](https://user-images.githubusercontent.com/72517844/95419191-62c81e00-0939-11eb-9883-e3e44ad7e72e.PNG)

![issue1](https://user-images.githubusercontent.com/72517844/95419203-665ba500-0939-11eb-8647-fca4e518893d.PNG)

**Comment by HawaiianSnow1337** [comment]
and in Call Stack it says language unknown

**Comment by Qiu233** [comment]
Just test the newest version.
Reopen this if you have any further question.
