### ISSUE TITLE
Drag the cross error

### ISSUE THREAD

**Issue by SharkyZapz** [ZQiu233/QTRHacker#11]
when i try to drag the cross to terraria this error pops up 

![image](https://user-images.githubusercontent.com/69469087/103706516-c0ccc780-4f61-11eb-842b-ede839a6cdd9.png)

**Comment by Qiu233** [comment]
This version is too old for 1.4.
Please wait, I'll post a new version for 1.4.1 and you'll be informed on github.

**Comment by Qiu233** [comment]
https://github.com/ZQiu233/QTRHacker/releases/tag/6.0.7676.23871
This version is for 1.4.1.2 but not completed.
Only several functions are OK.
Just make do with it.
