### ISSUE TITLE
如何编译中文的QTRHacker

### ISSUE THREAD

**Issue by ScatteredSnow** [ZQiu233/QTRHacker#13]
如何编译中文的QTRHacker

**Comment by Qiu233** [comment]
啊这，仓库默认的Configuration就是中文的，直接clone下来编译就好。
如果不是的话，可以手动把Configuration设置为Release，对应的就是中文的。

**Comment by ScatteredSnow** [comment]
我编译release QTRHack.exe会打不开。。

**Comment by Qiu233** [comment]
有错误提示吗？
任务管理器有进程出现吗？

**Comment by ScatteredSnow** [comment]
有进程但是一会就没了

**Comment by Qiu233** [comment]
建议进行调试，然后把出错的地方的错误发上来。

**Comment by ZQiu233** [comment]
Configuration选择Debug，然后再进行调试。

**Comment by ScatteredSnow** [comment]
启动选项怎么选择

**Comment by Qiu233** [comment]
> 启动选项怎么选择

什么意思，启动项目吗，在项目管理器(解决方案界面)里面找到QTRHacker.NewDimension，右键-设置为启动项目即可。

**Comment by ScatteredSnow** [comment]
![QQ图片20210119133345](https://user-images.githubusercontent.com/63265713/104991995-fc37bd80-5a5a-11eb-9dd2-f28dbe6151af.png)

**Comment by ScatteredSnow** [comment]
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=给定关键字不在字典中。
  Source=mscorlib
  StackTrace:
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 QTRHacker.NewDimension.Languages.Processor.get_Item(String n) 在 C:\Users\11316\Desktop\QTRHacker-master\QTRHacker.NewDimension\Languages\Processor.cs 中: 第 19 行
   在 QTRHacker.NewDimension.PagePanels.PagePanel_MainPage..ctor(Int32 Width, Int32 Height) 在 C:\Users\11316\Desktop\QTRHacker-master\QTRHacker.NewDimension\PagePanels\PagePanel_MainPage.cs 中: 第 72 行
   在 QTRHacker.NewDimension.MainForm..ctor() 在 C:\Users\11316\Desktop\QTRHacker-master\QTRHacker.NewDimension\MainForm.cs 中: 第 144 行
   在 QTRHacker.NewDimension.Program.Main() 在 C:\Users\11316\Desktop\QTRHacker-master\QTRHacker.NewDimension\Program.cs 中: 第 28 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    QTRHacker.NewDimension.Languages.Processor.this[string].get(string) (位于 Processor.cs 中)
    QTRHacker.NewDimension.PagePanels.PagePanel_MainPage.PagePanel_MainPage(int, int) (位于 PagePanel_MainPage.cs 中)
    QTRHacker.NewDimension.MainForm.MainForm() (位于 MainForm.cs 中)
    QTRHacker.NewDimension.Program.Main() (位于 Program.cs 中)

**Comment by Qiu233** [comment]
不对劲，可以在断点处，把key的内容发出来吗，我需要确定是哪个key出问题了。
这个问题不是第一次出现了，但是我也不知道为什么会这样。
在我的电脑上是没问题的，编译出来的修改器也是可用的，但其他人却无法编译成功。
我觉得跟字符集有关系。

**Comment by ScatteredSnow** [comment]
不大清楚什么情况，您可以向日葵看看吗

**Comment by ScatteredSnow** [comment]
n	"PlayerArrayAddress"	string
+		this	{QTRHacker.NewDimension.Languages.Processor}	QTRHacker.NewDimension.Languages.Processor
+		CrossImage	{System.Drawing.Bitmap}	System.Drawing.Image {System.Drawing.Bitmap}
+		PlayerArrayBaseAddressInfoView	null	QTRHacker.NewDimension.Controls.InfoView
+		this	{QTRHacker.NewDimension.PagePanels.PagePanel_MainPage, BorderStyle: System.Windows.Forms.BorderStyle.None}	QTRHacker.NewDimension.PagePanels.PagePanel_MainPage
+		ContentPanel	{System.Windows.Forms.Panel, BorderStyle: System.Windows.Forms.BorderStyle.None}	System.Windows.Forms.Panel
		ContentPanel.Width	296	int
+		MainPagePanel	null	QTRHacker.NewDimension.PagePanels.PagePanel
+		MainPanel	{System.Windows.Forms.Panel, BorderStyle: System.Windows.Forms.BorderStyle.None}	System.Windows.Forms.Panel
		MainPanel.Height	368	int
		pageWidth	296	int
+		this	{QTRHacker.NewDimension.MainForm, Text: QTRHacker-V6.0.7689.24624}	QTRHacker.NewDimension.MainForm
+		form	null	QTRHacker.NewDimension.MainForm

**Comment by ScatteredSnow** [comment]
是这些东西吗

**Comment by Qiu233** [comment]
不应该啊，很奇怪，让我看看

**Comment by Qiu233** [comment]
我检查了仓库里面，\QTRHacker.NewDimension\Languages\zh-cn.txt
是有PlayerArrayAddress这个项的，按理说不应该出现这个问题的。
具体的原因未知，我觉得跟字符集有关系。
要不然你输出一下读取到的Map检查一下是否有这个项。

**Comment by Qiu233** [comment]
你试试换成英文，也就是Configuration里面ENG再尝试编译一次，看看是否可以运行。
如果可以的话，那就很奇怪了。

**Comment by ScatteredSnow** [comment]
不行，显示System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=给定关键字不在字典中。
  Source=mscorlib
  StackTrace:
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 QTRHacker.NewDimension.PagePanels.PagePanel_MainPage..ctor(Int32 Width, Int32 Height)
   在 QTRHacker.NewDimension.MainForm..ctor()
   在 QTRHacker.NewDimension.Program.Main()

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

**Comment by ScatteredSnow** [comment]
我觉得您有空的话可以向日葵远程看看

**Comment by Qiu233** [comment]
英文也不行么，可以请你检查一下是否存在\QTRHacker.NewDimension\Languages\zh-cn.txt这个文件吗

**Comment by ScatteredSnow** [comment]
存在的

**Comment by Qiu233** [comment]
正在安装向日葵，请稍等

**Comment by ScatteredSnow** [comment]
好的

**Comment by ScatteredSnow** [comment]
识别码194640951

**Comment by Qiu233** [comment]
抱歉，在安装向日葵的时候遇到病毒，被安装大量垃圾软件，正在卸载，可以麻烦换一个远程平台吗
比如QQ远程控制，可以么

**Comment by ScatteredSnow** [comment]
可以的

**Comment by Qiu233** [comment]
我的QQ：2393868407

**Comment by Qiu233** [comment]
Fixed, reopen this issue if you have any other question.
