### ISSUE TITLE
Compile ENG

### ISSUE THREAD

**Issue by HawaiianSnow1337** [ZQiu233/QTRHacker#14]
Hey,

even when compile in ENG it start as Chinese version

**Comment by HawaiianSnow1337** [comment]
![Bild_2021-01-21_225958](https://user-images.githubusercontent.com/72517844/105417779-622f6b00-5c3c-11eb-8ffb-f3e972e87816.png)

so i put that manuell on ENG and now its working thank for your work <3  keep it up.

**Comment by Qiu233** [comment]
Sorry, I'll check it.

**Comment by Qiu233** [comment]
Emmm, as  I tested, it worked well when I choose configuration "ENG".
Reopen this issue if you have any other questions.

**Comment by Qiu233** [comment]
Oh I've found out the reason.
Please set the platform to x86.

**Comment by HawaiianSnow1337** [comment]
alright thank you
