### ISSUE TITLE
Crash with infinity ammo func.

### ISSUE THREAD

**Issue by erxson** [ZQiu233/QTRHacker#15]
For example: I have 23 arrows and im enabling Infinity Ammo. Im shooting 23 times and game CRASHED

**Comment by Qiu233** [comment]
Are you using a version built by yourself?
The latest release on github doesn't work for 1.4.1.2.

**Comment by erxson** [comment]
No, i used the latest release on chinese. I translated it on russian.

**Comment by erxson** [comment]
Anti debuff to crashing

**Comment by erxson** [comment]
and infinite flight

**Comment by ScatteredSnow** [comment]
What is your game version?

**Comment by erxson** [comment]
yes
but its crashed with chinese version

**Comment by erxson** [comment]
i thank that its crashing because im using not last version, then i compiled new version and its crashing, too

**Comment by erxson** [comment]
add more "enchantments" on weapons

**Comment by Qiu233** [comment]
Sorry for my lateness.
Anyway there's a complete version for 1.4.2.3 now.
Reopen this issue if you have any further questions.
