### ISSUE TITLE
Question regarding "Mechanical" effects

### ISSUE THREAD

**Issue by Relyze** [ZQiu233/QTRHacker#16]
Hello, I notice you aren't active on discord, I attempted to contact you there, but I wanted to ask how you reversed MechanicalRulerEffect and MechanicalGlassesEffect. I am trying to "port" your tool to TModLoader, any help is appreciated.

**Comment by Qiu233** [comment]
Sorry I wish I were not too late.
I think TML needs mod instead of memory hack,

**Comment by Relyze** [comment]
Hello, you were not too late. In your discord I released memory hack for TModLoader. It has few features that don't work, but I removed them. Can we talk on discord more?
