### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by BlockOG** [ZQiu233/QTRHacker#17]
The title basically says it all. I want linux support

**Comment by Qiu233** [comment]
It's hard to adapt for linux because of its completely different process/memory managing and .NET runtime.
In addition, there're few people playing Terraria on linux so it's not worth redeveloping I think.

**Comment by Qiu233** [comment]
I noticed that you have not commented anymore since this issue open.
Reopen it if you have any further question.
