### ISSUE TITLE
Question :D

### ISSUE THREAD

**Issue by Blenter1** [ZQiu233/QTRHacker#3]
Can I contact you somehow?

**Comment by Qiu233** [comment]
I'm glad to,but I don't know any way to do this.
I'm in China,there's a NET WALL built by government that blocked the way outwards.

**Comment by Blenter1** [comment]
Do you have a social network? Like A Discord?

**Comment by Qiu233** [comment]
> Do you have a social network? Like A Discord?

I've registered one,but I don't exactly know how to add a friend.
Maybe I should give you my name and the id following it.
Qiu#9127

**Comment by ZQiu233** [comment]
Emmmm in addition,I created a channel named "QTRHacker".
Here's the invitation link.
https://discord.gg/bzKc9vM

**Comment by Qiu233** [comment]
Emmmm in addition,I created a server named "QTRHacker".(I'm not sure if I should use the word 'server'.)
Here's the invitation link.
https://discord.gg/bzKc9vM
