### ISSUE TITLE
unlock jorney mode menu

### ISSUE THREAD

**Issue by erxson** [ZQiu233/QTRHacker#33]

**Comment by Qiu233** [comment]
In fact I haven't played this mode yet.
I'll look into it later.

**Comment by erxson** [comment]
I mean unlock menu, not items in menu

**Comment by erxson** [comment]
Make possible to open journey mode menu in default survival

**Comment by Qiu233** [comment]
Please check this release: [10.6.0.0](https://github.com/Qiu233/QTRHacker/releases/tag/10.6.0.0)
