### ISSUE TITLE
64 bit

### ISSUE THREAD

**Issue by spyro3112** [ZQiu233/QTRHacker#39]
Is it possible to make a 64 bit version so that it can work with tModLoader. Now it says that a 32 bit application cannot access 64 bit application data.

**Comment by Qiu233** [comment]
I'm working on this but encountered some problem.

**Comment by spyro3112** [comment]
Oh okay. Is it a difficult problem?

**Comment by spyro3112** [comment]
Is there an ETA for when the 64 bit will be out?

**Comment by TheSpiderDungeon** [comment]
Having the same issue.

**Comment by LV-cpu** [comment]
64位还有多久才能上线呢，期待

**Comment by LV-cpu** [comment]
I don't know how long it will take to get up to 64 bits

**Comment by LV-cpu** [comment]
I don't know how long it will take to launch 64 bit

**Comment by TheSpiderDungeon** [comment]
> I don't know how long it will take to launch 64 bit

64 位不可用。它正在制作中。

**Comment by Qiu233** [comment]
Guys please check this release: https://github.com/Qiu233/QTRHacker/releases/tag/11.2.0.0-1.4.3.6-TML
