### ISSUE TITLE
I Won't run it

### ISSUE THREAD

**Issue by bgdfbhsdfgsagra** [ZQiu233/QTRHacker#43]
![QQ截图20220803202431](https://user-images.githubusercontent.com/110529834/182622058-5b7e3b03-3b8e-4c5e-9080-c15d307fcee5.png)
![截图20220803213340](https://user-images.githubusercontent.com/110529834/182622135-a7d1a588-e0d5-418f-8cc7-52488092fb7c.png)

**Comment by Qiu233** [comment]
Please switch the combobox on top to the hack project named "QTRHacker".
