### ISSUE TITLE
Could not load file or assembly QHackCLR.dll

### ISSUE THREAD

**Issue by Ar41GG** [ZQiu233/QTRHacker#49]
![image](https://github.com/Qiu233/QTRHacker/assets/42722673/aa372f85-d86a-4470-890f-ed7fbbc5a709)
`Attaching failed due to an exception:
Could not load file or assembly 'E:\Games
blyat\qtr\13.0.0.0\QHackCLR.dil.The specified module was not found.
at
QHackLib.Q Hack Context…ctor(Int32 id)
at QHackLib.Q Hack Context.Create(Int32 pid)
at Qtracker.Core.Game Context…ctor(Process process)
at Tracker.Core. Game Context.Open Game(Process process)
at QTR Hacker.Hack Global.Initialize(Int32 pid)
at
QTRHacker.ViewModels.Page Panels.MainPageViewModel.Internal init(Php
oint p)`
Tried to re-download all versions of dotnet, 13 QTR, 12 QTR, Terraria, restarting pc and nothing works

**Comment by Ar41GG** [comment]
Btw like 3-5 days ago it works propertly. Only with .net 7 SDK x64

**Comment by Qiu233** [comment]
like some anti-malware is blocking that .dll file from being loaded.

**Comment by Ar41GG** [comment]
uh, but I disabled real-time windows defender ;c

**Comment by Ar41GG** [comment]
Always check closed tickets [https://github.com/Qiu233/QTRHacker/issues/42](url)
