### ISSUE TITLE
Injecting error

### ISSUE THREAD

**Issue by Hero425** [ZQiu233/QTRHacker#6]
When i move the cross into terraria im getting this error: 
![Screenshot_40](https://user-images.githubusercontent.com/65621114/82362837-402a7c80-9a0d-11ea-850e-55e511d0f058.png)

I have both .Net framework and VC runtime and i runned it as a administrator.

**Comment by DillonHankins** [comment]
Same exact problem, no idea why it does that

**Comment by Qiu233** [comment]
> Same exact problem, no idea why it does that

Sorry.
But doesn't it work?
I mean this one:https://github.com/ZQiu233/QTRHacker/releases/tag/5.1.7495.34237

**Comment by DillonHankins** [comment]
Yeah it works, i just had to run it as admin and use the latest version
