### ISSUE TITLE
I Don't Know How To Run It

### ISSUE THREAD

**Issue by spyro3112** [ZQiu233/QTRHacker#8]
I followed all the instructions and it is not running. Please help.

**Comment by Qiu233** [comment]
Emmm can you give some information about it.
Sorry maybe I'm too late for this.

**Comment by spyro3112** [comment]
I open QTRHacker.sln with visual studios 2017 I press ctrl f5 and it says error, a project with an output type of class library cannot be started directly. In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.

**Comment by spyro3112** [comment]
> Emmm can you give some information about it.
> Sorry maybe I'm too late for this.

Would it be possible for you to make a video on how to run it?

**Comment by Qiu233** [comment]
> I open QTRHacker.sln with visual studios 2017 I press ctrl f5 and it says error, a project with an output type of class library cannot be started directly. In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.

Oh, I think you should change the startup project.
You should find a project named "QTRHacker.NewDimension" in the "Solution Resource Manager"(translated from Chinese).Right click on it and choose "Set as startup project"(Also translated from Chinese).
Then try to press Ctrl+F5.

**Comment by spyro3112** [comment]
I set QTRHacker.NewDimension as the startup project and then I pressed ctrl f5 and nothing happens.

**Comment by Qiu233** [comment]
> I set QTRHacker.NewDimension as the startup project and then I pressed ctrl f5 and nothing happens.

That's strange.You should check the task manager if there's a process named "QTRHacker.exe".
By the way, if you find the hack is in Chinese, then change the "Solution Configuration" from "Release" to "Eng"(A combo box on the top side of VS).

**Comment by spyro3112** [comment]
There are is not a QTRHacker.exe in my task manager after doing it.

**Comment by Qiu233** [comment]
> There are is not a QTRHacker.exe in my task manager after doing it.

You just press F5 without ctrl and check if it's running.

**Comment by spyro3112** [comment]
![image](https://user-images.githubusercontent.com/70292490/93668132-b3460d00-fa58-11ea-8891-17f671c6003f.png)
this shows up

**Comment by Qiu233** [comment]
> ![image](https://user-images.githubusercontent.com/70292490/93668132-b3460d00-fa58-11ea-8891-17f671c6003f.png)
> this shows up

Try "Continue Debugging"

**Comment by spyro3112** [comment]
![image](https://user-images.githubusercontent.com/70292490/93690650-e6b08800-faa8-11ea-9e3b-4b42785231e2.png)
this shows up

**Comment by spyro3112** [comment]
> ![image](https://user-images.githubusercontent.com/70292490/93690650-e6b08800-faa8-11ea-9e3b-4b42785231e2.png)
> this shows up

That's strange.
Are you sure you had set "QTRHacker.NewDimension" as the startup project?

**Comment by spyro3112** [comment]
yes

**Comment by Qiu233** [comment]
OK, then I'd suggest you download the release instead of compiling it.
https://github.com/ZQiu233/QTRHacker/releases/tag/5.1.7495.34237

**Comment by spyro3112** [comment]
This release doesn't work for my game

**Comment by spyro3112** [comment]
I can't attach it
