### ISSUE TITLE
Urgently!

### ISSUE THREAD

**Issue by BlentER** [ZQiu233/QTRHacker#9]
When can you visit Discord? I have a lot to discuss with you!

**Comment by Qiu233** [comment]
Sorry,I've lost my exam this year and I'm now preparing the next exam(2021/6).

**Comment by Qiu233** [comment]
I've posted a newer update for 1.4.1.2.
Just check this.
https://github.com/ZQiu233/QTRHacker/releases/tag/6.0.7676.23871
Reopen this issue if you have any further question.
